'''Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.'''
from math import sqrt


def check_pentagonal(p_n):
    n = (sqrt(24 * p_n + 1) + 1) / 6
    return n == int(n)


assert(check_pentagonal(5) == True)
assert(check_pentagonal(4) == False)


def check_hexagonal(h_n):
    n = (1 + sqrt(1 + 8 * h_n)) / 4
    return n == int(n)


assert(check_hexagonal(6) == True)
assert(check_hexagonal(5) == False)

n = 286
Tn = n * (n + 1) / 2
while not(check_pentagonal(Tn)) or not(check_hexagonal(Tn)):
    n += 1
    Tn = int(n * (n + 1) / 2)
print(n, Tn)
